<?php

namespace App\Modules\InvoiceVerification\Services\Implementations;

use App\Modules\InvoiceVerification\Domain\Models\Transaction;
use App\Modules\InvoiceVerification\Services\Contracts\DocumentCompiler;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class PlaceholderDocumentCompiler implements DocumentCompiler
{
    public function compile(Transaction $transaction, array $documents, string $targetDirectory): array
    {
        $disk = config('invoice_verification.storage.compiled_disk');
        $fileName = sprintf('compiled-%s-%s.pdf', $transaction->registration_number, Str::lower(Str::random(6)));
        $path = trim($targetDirectory, '/').'/'.$fileName;

        $content = [
            'message' => 'Placeholder compiled document generated by compile adapter.',
            'transaction_id' => $transaction->id,
            'registration_number' => $transaction->registration_number,
            'compiled_at' => now()->toIso8601String(),
            'documents' => $documents,
        ];

        Storage::disk($disk)->put($path, json_encode($content, JSON_PRETTY_PRINT));

        return [
            'compiled_file_name' => $fileName,
            'compiled_file_disk' => $disk,
            'compiled_file_path' => $path,
            'total_files' => count($documents),
        ];
    }
}
